// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

/*
Package raymasson_users_email is a generated protocol buffer package.

It is generated from these files:
	users.proto

It has these top-level messages:
	UpdateEmailRequest
	UpdateEmailResponse
*/
package raymasson_users_email

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateEmailRequest struct {
	UserId   int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	NewEmail string `protobuf:"bytes,2,opt,name=new_email,json=newEmail" json:"new_email,omitempty"`
}

func (m *UpdateEmailRequest) Reset()                    { *m = UpdateEmailRequest{} }
func (m *UpdateEmailRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateEmailRequest) ProtoMessage()               {}
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateEmailRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type UpdateEmailResponse struct {
	// EmailBoss may clean up the email it receives to trim whitespace
	// or remove superfluous characters. The cleaned_email will be the
	// email actually stored after this cleaning.
	CleanedEmail string `protobuf:"bytes,1,opt,name=cleaned_email,json=cleanedEmail" json:"cleaned_email,omitempty"`
}

func (m *UpdateEmailResponse) Reset()                    { *m = UpdateEmailResponse{} }
func (m *UpdateEmailResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateEmailResponse) ProtoMessage()               {}
func (*UpdateEmailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateEmailResponse) GetCleanedEmail() string {
	if m != nil {
		return m.CleanedEmail
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateEmailRequest)(nil), "raymasson.users.email.UpdateEmailRequest")
	proto.RegisterType((*UpdateEmailResponse)(nil), "raymasson.users.email.UpdateEmailResponse")
}

func init() { proto.RegisterFile("users.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2d, 0x4e, 0x2d,
	0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2d, 0x4a, 0xac, 0xcc, 0x4d, 0x2c, 0x2e,
	0xce, 0xcf, 0xd3, 0x83, 0x08, 0xa7, 0xe6, 0x26, 0x66, 0xe6, 0x28, 0x79, 0x71, 0x09, 0x85, 0x16,
	0xa4, 0x24, 0x96, 0xa4, 0xba, 0x82, 0xb8, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xe2,
	0x5c, 0xec, 0x20, 0x45, 0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x6c, 0x20,
	0xae, 0x67, 0x8a, 0x90, 0x34, 0x17, 0x67, 0x5e, 0x6a, 0x79, 0x3c, 0x58, 0xaf, 0x04, 0x93, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x47, 0x5e, 0x6a, 0x39, 0x58, 0xb3, 0x92, 0x15, 0x97, 0x30, 0x8a, 0x59,
	0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xca, 0x5c, 0xbc, 0xc9, 0x39, 0xa9, 0x89, 0x79, 0xa9,
	0x29, 0x50, 0x7d, 0x8c, 0x60, 0x7d, 0x3c, 0x50, 0x41, 0xb0, 0x62, 0xa3, 0x42, 0x2e, 0x4e, 0x30,
	0xc3, 0x29, 0xbf, 0xb8, 0x58, 0x28, 0x85, 0x8b, 0x1b, 0xc9, 0x20, 0x21, 0x4d, 0x3d, 0xac, 0x6e,
	0xd7, 0xc3, 0x74, 0xb8, 0x94, 0x16, 0x31, 0x4a, 0x21, 0xee, 0x4a, 0x62, 0x03, 0x07, 0x8c, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x55, 0xf7, 0xfb, 0x5f, 0x27, 0x01, 0x00, 0x00,
}
